### ISSUE TITLE
Should tipe errors be catch by the consumer default fallback?

### ISSUE THREAD

**Issue by jleonardolemos** [convenia/Pigeon#111]
Tipe errors and internal erros are not captured for the default fallback since they dont extends `\Exception`.

All type of erros implements `\Throwable` then should we catch \Throwable instead of \Exception on default fallback?

**Comment by kauanslr** [comment]
I think it should be changed to `Throwable` since the initial idea of `fallback` is to recover the application from a unexpected behaviour where are any type of `Throwable`.

Your PR are welcome =)
