### ISSUE TITLE
 We can not install Pigeon in laravel 6.* up to 6.0

### ISSUE THREAD

**Issue by jleonardolemos** [convenia/Pigeon#112]
**Descripion**
We can not install Pigeon in laravel 6.* up to 6.0

**To Reproduce**
1. Fresh laravel istallation
2. require Pigeon

**To fix**
Change laravel dependency to 6.* instead of 6.0.*

**Comment by kauanslr** [comment]
Maybe fixed by #114

**Comment by jleonardolemos** [comment]
Success installation with laravel version 6, closing the issue.
