### ISSUE TITLE
basic_nack undefined function is called.

### ISSUE THREAD

**Issue by 2formaggi** [convenia/Pigeon#115]
**Describe the bug**
When calling user callback fails an undefined function is called.

**To Reproduce**
1. Create a broken consumer
2. Publish a message 
3. See error

**Expected behavior**
The reject action should be able to call basic ack.

**Environment (please complete the following information):**
 - PHP version: [e.g. 7.3.12]
 - Laravel version [5.8]
 - Pigeon version [1.3.1].

**Comment by 2formaggi** [comment]
I'd like to solve this issue.

**Comment by kauanslr** [comment]
Hey @2formaggi , can you provide the satcktrace of the exception?

**Comment by 2formaggi** [comment]
@kauanslr I couldn't reproduce the error anymore :thinking: 
I'll close this issue if it happen again, I'll reopen it and add the stack trace.
