### ISSUE TITLE
Should we send exceptions to sentry?

### ISSUE THREAD

**Issue by jleonardolemos** [convenia/Pigeon#128]
Can we have a configration with sentry dsn, if this is filled we can send the exceptions to sentry in default fallback

**Comment by kauanslr** [comment]
I think a configurable global fallback is a better solution, in that case you use the service container to set a fallback and in that fallback you can put your customizable excepition rules

**Comment by jleonardolemos** [comment]
Yeah, and we can override the default fallback, i will close this issue
