### ISSUE TITLE
There is no way to overwrite message properties

### ISSUE THREAD

**Issue by StefanoDucciConvenia** [convenia/Pigeon#134]
**Describe the bug**
When I pass the second parameter to publisher method the message properties doesn't change.

**To Reproduce**
1. Use the publish method passing a second parameter array with valid values
2. See that second parameter is completely ignored!

**Expected behavior**
When I pass or second parameter called properties, I expect this parameter to be used to replace as message properties.

**Environment (please complete the following information):**
 - PHP version: [e.g. 7.1.12]
 - Laravel version [6.18]
 - Pigeon version [1.6]

**Comment by jleonardolemos** [comment]
@kauanslr do you have any suggestion about this issue?

**Comment by jleonardolemos** [comment]
fixed on #136
