### ISSUE TITLE
vendor specific prefix

### ISSUE THREAD

**Issue by jleonardolemos** [convenia/Pigeon#137]
## Problem
Most of rabbitmq sas solutions that have webhook implementations consider a custom header prefix.
Cloudamqp consider a `-r` prefix for example.

## Proposal
A proposal for solutions is add a `prefix` configuration, if prefix is setted then we prepend it to headers.

**Comment by jleonardolemos** [comment]
@kauanslr what do you think about it?

**Comment by kauanslr** [comment]
just send your pr

**Comment by jleonardolemos** [comment]
Actually this is not necessary currently, lets wait for another request for this feature.
