### ISSUE TITLE
Add an assertNotPublished method

### ISSUE THREAD

**Issue by jleonardolemos** [convenia/Pigeon#192]
**Feature Description**
We have already an `assertNotDispatched` method, for event driven approach, lets write an `assertNotPublidhed` method to give the same possibility to simple message approach:

```php
Pigeon::fake()

Pigeon::assertNotPublished(queue, $arrayBody, $arrayHeaders);
```

**As we can see `assertNotPublished` has the headers as an optional argument, the method should check for headers only if the headers array is present, display the json when the verification fails can be a challenge too :)**

**Comment by jleonardolemos** [comment]
@LucasOtaviani what about this one?

**Comment by LucasOtaviani** [comment]
I think will be good, I'll spend some time on it!

**Comment by jleonardolemos** [comment]
@LucasOtaviani ???
